services:
  web:
    build: "./src/web/"
    ports:
      - "8000:8000"
    volumes:
      - "./src/web/:/app/"
  crd:
    build: "./src/crd/"
    ports:
      - "9222:9222"
    volumes:
      - "./src/crd/:/app/"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo/:/data/db/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: "mongo-express"
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
